"""added default uuid as gen_randon_uuid()

Revision ID: 92b61078114b
Revises: ed6d0ffd4e4a
Create Date: 2026-06-02 11:19:01.015100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92b61078114b'
down_revision: Union[str, Sequence[str], None] = 'ed6d0ffd4e4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
