"""added google sub

Revision ID: ed6d0ffd4e4a
Revises: 68d19a89ec16
Create Date: 2026-06-02 11:05:10.115593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed6d0ffd4e4a'
down_revision: Union[str, Sequence[str], None] = '68d19a89ec16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_sub', sa.TEXT(), nullable=True))
    op.create_unique_constraint(None, 'users', ['google_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'google_sub')
    # ### end Alembic commands ###
